---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: gp2-encrypted
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    name: storage-class-test
    app: storage-class-test
  name: storage-class-test
spec:
  containers:
    - image: nginx
      name: webserver
      ports:
        - containerPort: 80
          name: http
      volumeMounts:
        - mountPath: /tmp/nginx
          name: app-data
      resources:
        requests:
          cpu: 100m
          memory: 100Mi
        limits:
          cpu: 100m
          memory: 100Mi
  volumes:
    - name: app-data
      persistentVolumeClaim:
        claimName: test-pvc
