name: Release
on:
  push:
    branches:
      - main
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    # Skip running release workflow on forks
    if: github.repository_owner == 'stuxcd'
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Release
        uses: cycjimmy/semantic-release-action@v3
        with:
          semantic_version: 1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}